### ISSUE TITLE
Create SQLite automatically using sqlite-utils

### ISSUE THREAD

**Issue by rtanglao** [thunderbird/github-action-thunderbird-aaq#4]
* Create SQLite databases automaticaly using sqlite-utils; * Check out [Stefan Kühnel''s workflow](https://github.com/bystefankuehnel/naruto.dvd.stefan-dev.de/blob/main/.github/workflows/vercel.yml), specifically:
```yaml
name: Vercel

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download Excel SpreedSheet
        run: curl -Lo excel.xlsx https://docs.google.com/spreadsheets/d/1by2mZB4-ixVfRAu-_mcRxyQEJGuSfbzPkh-AlrUPCLY/export?format=xlsx
      - name: Download CSV
        run: curl -Lo collection.csv https://docs.google.com/spreadsheets/d/1by2mZB4-ixVfRAu-_mcRxyQEJGuSfbzPkh-AlrUPCLY/export?format=csv
      - name: Create SQLite Database
        run: sqlite-utils insert collection.db collection collection.csv --csv
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |-
          datasette publish vercel collection.db \
            --branch main \
            --metadata metadata.json \
            --token $VERCEL_TOKEN \
            --project naruto-shippuden-datasette-stefan-dev-de \
            --install datasette-graphql \
            --public
      - name: Delete Previous Release
        continue-on-error: true
        run: gh release delete latest --cleanup-tag --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        run: |-
          gh release create latest \
            --latest \
            --title "Release" \
            --notes "**Version**: $(date +"%Y%m%d")-git-${GITHUB_SHA:0:7}" \
            "excel.xlsx"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
